name: Common setup for peer-observer nix-based workflows
description: Checkout repo and install nix

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-25.11
