name: Common setup for peer-observer ubuntu-based workflows
description: Install dependencies

runs:
  using: composite
  steps:
    - name: Install build dependecies
      shell: bash
      run: |
        sudo apt update -y
        sudo apt-get install -y \
          protobuf-compiler \
          libelf-dev \
          clang \
          llvm \
          llvm-14 \
          zstd \
          binutils-dev \
          elfutils \
          gcc-multilib
